version: '3'
services:
  application:
    container_name: hadouken
    image: hadouken
    build: .
    ports:
      - "${PORT:-1337}:${PORT:-1337}"
    environment:
      - PORT=${PORT:-1337}
      - MYSQL_MAX_RETRIES=1
      - MYSQL_HOST=172.30.97.185
      - MYSQL_PORT=8080
      - MYSQL_USER=user1
      - MYSQL_PASSWORD=test123
      - MYSQL_DATABASE=metrics
      - MYSQL_CONNECTION_LIMIT=300
      - MYSQL_WAIT_FOR_CONNECTIONS=true
      - MYSQL_QUEUE_LIMIT=300
      - MYSQL_ACQUIRE_TIMEOUT=60000
      - MYSQL_TIMEOUT=60000
      - MYSQL_DEBUG=false
